FROM node:20-bullseye
WORKDIR /app

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

RUN corepack enable && corepack prepare pnpm@9.15.4 --activate

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --reporter=append-only

COPY . .

CMD ["pnpm", "db:migrate"]
