import { NextRequest, NextResponse } from 'next/server';
import db from '@/lib/db';
import { levelSchema } from '@/lib/models/validators/level';
import debug from 'debug';

const logger = debug('ui_designer:api:levels');

const respondWithError = (error: any, status: number = 400) => {
  logger('%O', error);
  return NextResponse.json({ error: error.message }, { status });
};

export async function GET(request: NextRequest) {
  try {
    const levels = await db.Level.findAll();
    logger('Found %d levels', levels.length);
    return NextResponse.json(
      levels.map((level: any) => ({
        identifier: level.identifier,
        name: level.name,
        ...level.json,
      }))
    );
  } catch (error: any) {
    logger('Error: %O', error);
    return NextResponse.json(
      { message: 'Failed to fetch levels' },
      { status: 500 }
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { value, error } = levelSchema.tailor('create').validate(body);
    if (error) return respondWithError(error);

    const { name, ...json } = value;
    // identifier is auto-generated by Sequelize with UUIDV1 default, so we omit it
    // @ts-expect-error - identifier has a default value in the model but TypeScript doesn't recognize it as optional
    const level = await db.Level.create({ 
      name, 
      json,
    });

    return level
      ? NextResponse.json(
          {
            identifier: level.identifier,
            name: level.name,
            ...level.json,
          },
          { status: 201 }
        )
      : NextResponse.json(
          { message: 'Failed to create new level' },
          { status: 500 }
        );
  } catch (error: any) {
    logger('Error %O', error);
    return NextResponse.json(
      { message: 'Failed to create level' },
      { status: 500 }
    );
  }
}

